name: telegram-bot
services:
  - name: bot
    type: web
    ports:
      - port: 8080
        protocol: http
    routes:
      - path: /
        protocol: http
    env:
      - name: API_ID
        value: "20094764"
      - name: API_HASH
        value: "ac33c77cfdbe4f94ebd73dde27b4a10c"
      - name: BOT_TOKEN
        value: "7246099288:AAGEgP5hFkY3NJicptMgHInQ1APDTMBJT8M"
      - name: DEFAULT_2FA_PASSWORD
        value: "112233"
      - name: MONGO_URI
        value: "mongodb+srv://noob:K3a4ofLngiMG8Hl9@tele.fjm9acq.mongodb.net/?retryWrites=true&w=majority"
      - name: REQUESTED_CHANNEL
        value: "@TGVIPR"
      - name: WITHDRAWAL_LOG_CHAT_ID
        value: "-1002626888395"
      - name: ADMIN_IDS
        value: "1211362365"
      - name: SESSIONS_DIR
        value: "sessions"
      - name: VERIFIED_DIR
        value: "verified"
    build:
      dockerfile: Dockerfile
    resources:
      cpu: 0.5
      memory: 512Mi
    scaling:
      min: 1
      max: 1
    healthcheck:
      path: /health
      port: 8080
      interval: 30s
      timeout: 10s
      retries: 3